import { NextResponse } from 'next/server';
import { supabaseServiceRole } from '@autohub360/auth/server';
import { getEmailAdapter, getWhatsAppAdapter, renderTemplate } from '@autohub360/integrations';
import { hasAdminSession } from '@/lib/admin-session';

export const runtime='nodejs';

async function authorized(request:Request,allowSession:boolean){const cron=process.env.CRON_SECRET;const bearer=request.headers.get('authorization');if(cron&&bearer===`Bearer ${cron}`)return true;return allowSession?hasAdminSession():false;}

async function dispatch(){const db=supabaseServiceRole();if(!db)return NextResponse.json({ok:false,error:'DB indisponível.'},{status:503});const now=new Date().toISOString();const {data:rows,error}=await db.from('notification_outbox').select('*').eq('status','queued').lte('scheduled_for',now).order('scheduled_for').limit(30);if(error)return NextResponse.json({ok:false,error:error.message},{status:500});let sent=0,blocked=0,failed=0;for(const row of rows??[]){const {data:template}=await db.from('notification_templates').select('*').eq('code',row.template_code).eq('market',row.market).eq('channel',row.channel).eq('status','active').maybeSingle();if(!template){blocked++;await db.from('notification_outbox').update({error:'Template ativo não encontrado.'}).eq('id',row.id);continue;}const payload=(row.payload??{}) as Record<string,unknown>;const body=renderTemplate(template.body,payload);const subject=template.subject?renderTemplate(template.subject,payload):'AutoHub360';let result:{ok:boolean;ref?:string;error?:string};if(row.channel==='email'){const adapter=getEmailAdapter();if(adapter.id==='noop'){blocked++;await db.from('notification_outbox').update({error:'EMAIL_PROVIDER não configurado.'}).eq('id',row.id);continue;}result=await adapter.send({to:row.destination,subject,html:`<div style="font-family:Arial,sans-serif;line-height:1.6">${body.replaceAll('\n','<br/>')}</div>`,metadata:{outbox_id:row.id}});}else if(row.channel==='whatsapp'){const adapter=getWhatsAppAdapter();if(adapter.id==='noop'){blocked++;await db.from('notification_outbox').update({error:'WHATSAPP_PROVIDER não configurado.'}).eq('id',row.id);continue;}result=await adapter.send({to:row.destination,text:body,metadata:{outbox_id:row.id}});}else{blocked++;await db.from('notification_outbox').update({error:'Canal ainda sem adapter.'}).eq('id',row.id);continue;}if(result.ok){sent++;await db.from('notification_outbox').update({status:'sent',sent_at:new Date().toISOString(),attempts:(row.attempts??0)+1,provider_ref:result.ref??null,error:null}).eq('id',row.id);}else{failed++;await db.from('notification_outbox').update({status:'failed',attempts:(row.attempts??0)+1,error:result.error??'Falha de envio.'}).eq('id',row.id);}}return NextResponse.json({ok:true,processed:(rows??[]).length,sent,blocked,failed});}

export async function POST(request:Request){if(!(await authorized(request,true)))return NextResponse.json({ok:false,error:'Não autorizado.'},{status:401});return dispatch();}
export async function GET(request:Request){if(!(await authorized(request,false)))return NextResponse.json({ok:false,error:'Cron não autorizado.'},{status:401});return dispatch();}
