import { Bot, LifeBuoy } from 'lucide-react';
import { SupportAIButton } from '@/components/support-ai-button';
import { EmptyState, MetricCard, PageHeading, Panel, StatusBadge } from '@/components/admin-ui';
import { adminDb, formatDate } from '@/lib/admin-data';

export const metadata={title:'Pós-venda IA'};
export default async function SupportPage(){const db=adminDb();if(!db)return <EmptyState text="Supabase não configurado."/>;const [casesR,messagesR,contactsR,ordersR]=await Promise.all([db.from('support_cases').select('*').order('updated_at',{ascending:false}).limit(50),db.from('support_messages').select('*').order('created_at',{ascending:false}).limit(120),db.from('crm_contacts').select('id,full_name,email,phone'),db.from('orders').select('id,number,status')]);const cases=casesR.data??[];const messages=messagesR.data??[];const contactMap=new Map((contactsR.data??[]).map((c)=>[c.id,c]));const orderMap=new Map((ordersR.data??[]).map((o)=>[o.id,o]));return <div className="space-y-6"><PageHeading title="Pós-venda assistido por IA" description="Tickets unificados por contacto/pedido. A IA cria rascunhos privados para revisão humana; não inventa política, status ou garantia e pode ser escalada para agente."/>
<div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Tickets" value={String(cases.length)} icon={<LifeBuoy className="h-4 w-4"/>}/><MetricCard label="Abertos" value={String(cases.filter((c)=>['open','ai_handling','waiting_team'].includes(c.status)).length)} tone="orange"/><MetricCard label="IA habilitada" value={String(cases.filter((c)=>c.ai_enabled).length)} icon={<Bot className="h-4 w-4"/>} tone="violet"/><MetricCard label="Resolvidos" value={String(cases.filter((c)=>c.status==='resolved').length)} tone="green"/></div>
<div className="space-y-4">{cases.map((c)=>{const contact=contactMap.get(c.contact_id);const order=orderMap.get(c.order_id);const thread=messages.filter((m)=>m.case_id===c.id).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());return <Panel key={c.id}><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-black text-white">{c.ticket} · {c.subject}</p><StatusBadge value={c.status}/><StatusBadge value={c.priority}/></div><p className="mt-1 text-[11px] text-slate-500">{contact?.full_name||contact?.email||'Contacto não vinculado'} {order?`· pedido ${order.number}`:''} · {formatDate(c.updated_at)}</p></div>{c.ai_enabled?<SupportAIButton caseId={c.id}/>:null}</div><div className="mt-4 space-y-2">{thread.map((m)=><div key={m.id} className={`rounded-xl border p-3 ${m.author_type==='customer'?'border-blue-500/15 bg-blue-500/[0.05]':m.author_type==='ai'?'border-violet-500/15 bg-violet-500/[0.05]':'border-white/7 bg-black/15'}`}><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{m.author_type}{m.visible_to_customer?'':' · rascunho privado'}</p><time className="text-[9px] text-slate-600">{formatDate(m.created_at)}</time></div><p className="mt-2 whitespace-pre-wrap text-xs leading-relaxed text-slate-300">{m.body}</p></div>)}</div></Panel>})}{cases.length===0?<EmptyState text="Nenhum ticket pós-venda ainda."/>:null}</div></div>}
