import Link from 'next/link';
import { ExternalLink, PackageCheck, ShoppingBag } from 'lucide-react';
import { ShipmentEventForm } from '@/components/shipment-event-form';
import { EmptyState, MetricCard, PageHeading, Panel, StatusBadge } from '@/components/admin-ui';
import { adminDb, formatDate, formatMoney } from '@/lib/admin-data';

export const metadata={title:'Pedidos & Tracking'};
export default async function OperationsPage(){const db=adminDb();if(!db)return <EmptyState text="Supabase não configurado."/>;const [ordersR,shipR,eventsR]=await Promise.all([db.from('orders').select('*').order('created_at',{ascending:false}).limit(50),db.from('shipments').select('*').order('updated_at',{ascending:false}).limit(50),db.from('shipment_events').select('*').order('occurred_at',{ascending:false}).limit(60)]);const orders=ordersR.data??[];const shipments=shipR.data??[];const orderMap=new Map(orders.map((o)=>[o.id,o]));const store=process.env.NEXT_PUBLIC_STORE_URL||'https://autohub360.store';return <div className="space-y-6"><PageHeading title="Pedidos & Tracking" description="Controla pedido, expedição, tracking público e eventos de entrega. Cada nova etapa alimenta CRM e automações de comunicação."/>
<div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Pedidos" value={String(orders.length)} icon={<ShoppingBag className="h-4 w-4"/>}/><MetricCard label="Expedições" value={String(shipments.length)} icon={<PackageCheck className="h-4 w-4"/>}/><MetricCard label="Em trânsito" value={String(shipments.filter((s)=>['in_transit','out_for_delivery'].includes(s.status)).length)} tone="orange"/><MetricCard label="Entregues" value={String(shipments.filter((s)=>s.status==='delivered').length)} tone="green"/></div>
<div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><Panel title="Registrar etapa logística" subtitle="Aceita o código público AH… ou o tracking da transportadora."><ShipmentEventForm/></Panel><Panel title="Expedições"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wide text-slate-600"><tr><th className="pb-3">Pedido</th><th>Status</th><th>Transportadora</th><th>Tracking</th><th>Atualização</th><th></th></tr></thead><tbody className="divide-y divide-white/6">{shipments.map((s)=>{const o=orderMap.get(s.order_id);return <tr key={s.id}><td className="py-3"><p className="font-bold text-white">{o?.number??'—'}</p><p className="text-slate-500">{o?.customer_name??'—'}</p></td><td><StatusBadge value={s.status}/></td><td className="text-slate-400">{s.carrier||'—'}</td><td><p className="font-mono text-[11px] text-blue-300">{s.public_code??'—'}</p><p className="font-mono text-[10px] text-slate-600">{s.tracking_code??''}</p></td><td className="text-slate-500">{formatDate(s.last_event_at??s.updated_at)}</td><td><Link target="_blank" href={`${store}/rastrear/${s.public_code}`} className="inline-flex items-center gap-1 text-[10px] font-bold text-blue-300 hover:text-white">Público <ExternalLink className="h-3 w-3"/></Link></td></tr>})}</tbody></table>{shipments.length===0?<EmptyState text="Nenhuma expedição criada."/>:null}</div></Panel></div>
<Panel title="Pedidos recentes"><div className="grid gap-2 lg:grid-cols-2">{orders.map((o)=><div key={o.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/7 bg-black/15 p-3"><div><div className="flex items-center gap-2"><p className="text-xs font-bold text-white">{o.number}</p>{o.demo?<span className="rounded bg-violet-500/10 px-1.5 py-.5 text-[9px] font-bold text-violet-300">DEMO</span>:null}</div><p className="mt-1 text-[11px] text-slate-500">{o.customer_name} · {formatDate(o.created_at)}</p></div><div className="text-right"><StatusBadge value={o.status}/><p className="mt-1 text-xs font-bold text-white">{formatMoney(o.total_cents,String(o.currency).trim())}</p></div></div>)}{orders.length===0?<EmptyState text="Sem pedidos."/>:null}</div></Panel>
<Panel title="Timeline logística"><div className="space-y-2">{(eventsR.data??[]).slice(0,20).map((e)=><div key={e.id} className="flex items-start gap-3 rounded-xl border border-white/7 bg-black/15 p-3"><span className="mt-1.5 h-2 w-2 rounded-full bg-blue-400"/><div className="flex-1"><div className="flex items-center gap-2"><p className="text-xs font-bold text-white">{e.title}</p><StatusBadge value={e.status}/></div><p className="mt-1 text-[11px] text-slate-500">{e.description||'Sem descrição'} {e.location?`· ${e.location}`:''}</p></div><time className="text-[10px] text-slate-600">{formatDate(e.occurred_at)}</time></div>)}</div></Panel></div>}
