import { createHash } from 'node:crypto';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { supabaseServiceRole } from '@autohub360/auth/server';
import { clientIp, rateLimit } from '@autohub360/integrations';

export const runtime='nodejs';
const schema=z.object({sessionId:z.string().min(8).max(120),eventType:z.string().min(2).max(80),path:z.string().max(1000).optional(),market:z.enum(['BR','EU']).default('BR'),referrer:z.string().max(1200).optional(),utmSource:z.string().max(180).optional(),utmMedium:z.string().max(180).optional(),utmCampaign:z.string().max(220).optional(),utmContent:z.string().max(220).optional(),utmTerm:z.string().max(220).optional(),device:z.string().max(40).optional(),productId:z.string().uuid().optional(),metadata:z.record(z.unknown()).optional()});
export async function POST(request:Request){const ip=clientIp(request.headers);const limit=rateLimit(`webtrack:${ip}`,90,60_000);if(!limit.ok)return NextResponse.json({ok:false},{status:429});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false},{status:422});const db=supabaseServiceRole();if(!db)return NextResponse.json({ok:true,stored:false});const d=parsed.data;const now=new Date().toISOString();const salt=process.env.WEBTRACKING_HASH_SALT;const ipHash=salt&&ip?createHash('sha256').update(`${salt}:${ip}`).digest('hex'):null;const {data:existing}=await db.from('web_sessions').select('id,event_count,first_path,utm_source,utm_medium,utm_campaign,utm_content,utm_term').eq('session_id',d.sessionId).maybeSingle();if(existing){await db.from('web_sessions').update({last_path:d.path??null,last_seen_at:now,event_count:(existing.event_count??0)+1,referrer:d.referrer??undefined,utm_source:existing.utm_source??d.utmSource??null,utm_medium:existing.utm_medium??d.utmMedium??null,utm_campaign:existing.utm_campaign??d.utmCampaign??null,utm_content:existing.utm_content??d.utmContent??null,utm_term:existing.utm_term??d.utmTerm??null,device:d.device??null,ip_hash:ipHash??undefined}).eq('id',existing.id);}else{await db.from('web_sessions').insert({session_id:d.sessionId,market:d.market,first_path:d.path??null,last_path:d.path??null,referrer:d.referrer??null,utm_source:d.utmSource??null,utm_medium:d.utmMedium??null,utm_campaign:d.utmCampaign??null,utm_content:d.utmContent??null,utm_term:d.utmTerm??null,device:d.device??null,ip_hash:ipHash,event_count:1,first_seen_at:now,last_seen_at:now});}await db.from('lead_events').insert({session_id:d.sessionId,event_type:d.eventType,source:d.utmSource??'web',path:d.path??null,product_id:d.productId??null,metadata:{market:d.market,referrer:d.referrer,utm_source:d.utmSource,utm_medium:d.utmMedium,utm_campaign:d.utmCampaign,utm_content:d.utmContent,utm_term:d.utmTerm,device:d.device,...(d.metadata??{})}});return NextResponse.json({ok:true,stored:true});}
