import { Megaphone, MousePointerClick, Target } from 'lucide-react';
import { EmptyState, MetricCard, PageHeading, Panel, StatusBadge } from '@/components/admin-ui';
import { adminDb, formatDate } from '@/lib/admin-data';

export const metadata={title:'Marketing'};
export default async function MarketingPage(){const db=adminDb();if(!db)return <EmptyState text="Supabase não configurado."/>;const [campaignsR,sessionsR,leadsR]=await Promise.all([db.from('campaigns').select('*').order('updated_at',{ascending:false}),db.from('web_sessions').select('*').order('last_seen_at',{ascending:false}).limit(500),db.from('leads').select('*').order('created_at',{ascending:false}).limit(500)]);const campaigns=campaignsR.data??[];const sessions=sessionsR.data??[];const leads=leadsR.data??[];const sources=new Map<string,{sessions:number;leads:number}>();for(const s of sessions){const key=s.utm_source||'direto';sources.set(key,{sessions:(sources.get(key)?.sessions??0)+1,leads:sources.get(key)?.leads??0});}for(const l of leads){const key=l.utm_source||l.source||'direto';sources.set(key,{sessions:sources.get(key)?.sessions??0,leads:(sources.get(key)?.leads??0)+1});}return <div className="space-y-6"><PageHeading title="Marketing & aquisição" description="Campanhas, origem de tráfego, sessões consentidas, leads e funis /ofertas. A atribuição permanece first-party e separada dos pixels externos."/>
<div className="grid gap-3 sm:grid-cols-3"><MetricCard label="Campanhas" value={String(campaigns.length)} icon={<Megaphone className="h-4 w-4"/>}/><MetricCard label="Sessões" value={String(sessions.length)} icon={<MousePointerClick className="h-4 w-4"/>} tone="violet"/><MetricCard label="Leads" value={String(leads.length)} icon={<Target className="h-4 w-4"/>} tone="orange"/></div>
<div className="grid gap-5 xl:grid-cols-2"><Panel title="Campanhas"><div className="space-y-2">{campaigns.map((c)=><div key={c.id} className="rounded-xl border border-white/7 bg-black/15 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-white">{c.name}</p><p className="mt-1 text-[11px] text-slate-500">{c.code} · {c.market} · {c.placement}</p></div><StatusBadge value={c.status}/></div><p className="mt-2 text-xs text-slate-400">{c.headline}</p>{c.cta_url?<p className="mt-1 font-mono text-[10px] text-blue-300">{c.cta_url}</p>:null}</div>)}{campaigns.length===0?<EmptyState text="Sem campanhas."/>:null}</div></Panel><Panel title="Aquisição por origem"><div className="space-y-2">{[...sources.entries()].sort((a,b)=>b[1].sessions-a[1].sessions).slice(0,15).map(([source,v])=><div key={source} className="grid grid-cols-[1fr_70px_70px] items-center gap-3 rounded-xl border border-white/7 bg-black/15 p-3"><p className="truncate text-xs font-semibold text-white">{source}</p><div className="text-right"><p className="text-xs font-bold text-blue-300">{v.sessions}</p><p className="text-[9px] text-slate-600">sessões</p></div><div className="text-right"><p className="text-xs font-bold text-orange-300">{v.leads}</p><p className="text-[9px] text-slate-600">leads</p></div></div>)}{sources.size===0?<EmptyState text="Atribuição ainda sem dados."/>:null}</div></Panel></div>
<Panel title="Leads recentes"><div className="grid gap-2 lg:grid-cols-2">{leads.slice(0,20).map((l)=><div key={l.id} className="rounded-xl border border-white/7 bg-black/15 p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold text-white">{l.name||l.email}</p><StatusBadge value={l.status}/></div><p className="mt-1 text-[11px] text-slate-500">{[l.utm_source,l.utm_medium,l.utm_campaign].filter(Boolean).join(' / ')||l.source||'origem não informada'} · {formatDate(l.created_at)}</p></div>)}</div></Panel></div>}
