import { Boxes, Link2, Truck } from 'lucide-react';
import { EmptyState, MetricCard, PageHeading, Panel, StatusBadge } from '@/components/admin-ui';
import { adminDb, formatDate, formatMoney } from '@/lib/admin-data';

export const metadata={title:'Catálogo & Sourcing'};
export default async function CatalogPage(){const db=adminDb();if(!db)return <EmptyState text="Supabase não configurado."/>;const [productsR,offersR,suppliersR,marketsR]=await Promise.all([db.from('products').select('id,sku,title,price_cents,currency,published,stock,category_id').order('created_at',{ascending:false}),db.from('product_supplier_offers').select('*').order('updated_at',{ascending:false}),db.from('suppliers').select('*').order('name'),db.from('product_market_offers').select('*')]);const products=productsR.data??[];const offers=offersR.data??[];const suppliers=suppliersR.data??[];const productMap=new Map(products.map((p)=>[p.id,p]));const supplierMap=new Map(suppliers.map((s)=>[s.id,s]));return <div className="space-y-6"><PageHeading title="Catálogo & Sourcing" description="Produtos reais-first, custo observado, origem, vendedor, URL e status de direct shipping. Oferta de marketplace não é tratada como fornecedor homologado até validação."/>
<div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Produtos" value={String(products.length)} icon={<Boxes className="h-4 w-4"/>}/><MetricCard label="Fontes" value={String(suppliers.length)} icon={<Link2 className="h-4 w-4"/>} tone="violet"/><MetricCard label="Ofertas source" value={String(offers.length)} tone="orange"/><MetricCard label="Direct ship validado" value={String(offers.filter((o)=>['approved','validated'].includes(o.direct_ship_status)).length)} icon={<Truck className="h-4 w-4"/>} tone="green"/></div>
<Panel title="Sourcing real"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wide text-slate-600"><tr><th className="pb-3">Produto</th><th>Fonte</th><th>Custo</th><th>Preço BR</th><th>Margem bruta</th><th>Fulfillment</th><th>Observado</th><th>Link</th></tr></thead><tbody className="divide-y divide-white/6">{offers.map((o)=>{const p=productMap.get(o.product_id);const s=supplierMap.get(o.supplier_id);const cost=Number(o.cost_cents??0);const price=Number(p?.price_cents??0);const margin=price>0?((price-cost)/price)*100:0;return <tr key={o.id}><td className="py-3 pr-4"><p className="font-semibold text-white">{p?.title??'Produto'}</p><p className="font-mono text-[10px] text-slate-600">{p?.sku??o.supplier_sku??'—'}</p></td><td><p className="text-slate-300">{o.source_marketplace??s?.name??'—'}</p><p className="text-[10px] text-slate-600">{o.source_seller??''}</p></td><td className="font-semibold text-slate-300">{formatMoney(cost,String(o.source_currency??'BRL').trim())}</td><td className="font-semibold text-blue-300">{formatMoney(price,String(p?.currency??'BRL').trim())}</td><td className={margin>=30?'text-emerald-300':'text-amber-300'}>{margin.toFixed(1)}%</td><td><StatusBadge value={o.direct_ship_status}/></td><td className="text-slate-500">{formatDate(o.source_observed_at??o.last_synced_at)}</td><td>{o.source_url?<a href={o.source_url} target="_blank" rel="noopener noreferrer" className="text-blue-300 hover:text-white">abrir ↗</a>:'—'}</td></tr>})}</tbody></table>{offers.length===0?<EmptyState text="Sem ofertas de sourcing."/>:null}</div></Panel>
<Panel title="Mercados"><div className="grid gap-2 sm:grid-cols-2">{(marketsR.data??[]).map((m)=><div key={m.id} className="flex items-center justify-between rounded-xl border border-white/7 bg-black/15 p-3"><div><p className="text-xs font-bold text-white">Produto {String(m.product_id).slice(0,8)}</p><p className="text-[10px] text-slate-500">{m.market} · {String(m.currency).trim()} · stock {m.stock}</p></div><StatusBadge value={m.active?'active':'draft'}/></div>)}</div></Panel></div>}
